Mango.Web/Controllers/AuthController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace Mango.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        private ResponseDto _responseDto;

        public AuthController(IAuthService authService,
                              ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
            _responseDto = new ResponseDto();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDto loginDto)
        {
            if (ModelState.IsValid)
            {
                _responseDto = await _authService.Login(loginDto);
                
                if(_responseDto != null && !string.IsNullOrWhiteSpace(_responseDto.Message))
                {
                    TempData["Error"] = _responseDto.Message;
                    return View(loginDto);
                }

                var result = JsonConvert.DeserializeObject<DeserializeHandlerForLogin>(Convert.ToString(_responseDto.Result));
                
                var loginResponseDto = result.Result;
                
                _tokenProvider.SetToken(loginResponseDto.Token);

                await SignInUser(loginResponseDto);

                return RedirectToAction("Index", "Home");
            }       
            
            return View(loginDto);
        }

        [HttpGet]
        public IActionResult RegisterUser()
        {
            RegisterRequestDto registerUserDto = new();
            registerUserDto.Roles = PopulateRoles();
                                                                     
            return View(registerUserDto);
        }

        [HttpPost]
        public async Task<IActionResult> RegisterUser(RegisterRequestDto registerUserDto)
        {
            if(ModelState.IsValid)
            {
                _responseDto = await _authService.RegisterUser(registerUserDto);

                ResponseDto assignRole;

                if (_responseDto != null && _responseDto.IsSuccess)
                {
                    if (!registerUserDto.MultiRoles.Any())
                    {
                        registerUserDto.MultiRoles.Add("Guest");
                    }

                    assignRole = await _authService.AssignRole(registerUserDto);
                    if (!assignRole.IsSuccess)
                    {
                        TempData["Error"] = assignRole.Message;
                    }

                    TempData["Success"] = "User is successfully registered.";
                    
                    return RedirectToAction("Login");
                }
            }
            
            ModelState.AddModelError("Errors", _responseDto.Message);

            registerUserDto.Roles = PopulateRoles();
            
            return View(registerUserDto);
        }

        [HttpGet]
        public async Task<IActionResult> Signout()
        {
            _tokenProvider.ClearToken();     
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult AccessDenied()
        {
            return View();
        }

        private async Task SignInUser(LoginResponseDto loginResponseDto)
        {
            var tokenHandler = new JwtSecurityTokenHandler();
            var jwt =  tokenHandler.ReadJwtToken(loginResponseDto.Token);

            var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
            
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub).Value));
            identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));

            identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Name).Value));
            identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(u => u.Type == "role").Value));
            identity.AddClaim(new Claim(ClaimTypes.MobilePhone, jwt.Claims.FirstOrDefault(u => u.Type == ClaimTypes.MobilePhone).Value));

            var principal = new ClaimsPrincipal(identity);            
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,principal);

        }

        private static List<SelectListItem> PopulateRoles()
        {
            return new()
            {
                new SelectListItem("SuperAdmin", "SuperAdmin"),
                new SelectListItem("Admin", "Admin"),
                new SelectListItem("User", "User"),
                new SelectListItem("Guest", "Guest"),
            };
        }
    }
}

Mango.Web/Controllers/CouponController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Mango.Web.Utilities;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Dynamic;

namespace Mango.Web.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;

        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var responseDto = await _couponService.GetCouponsAsync();
            var coupons = new List<CouponDto>();

            
            if(responseDto != null && responseDto.IsSuccess) 
            {
               var handleForList = JsonConvert.DeserializeObject<DeserializeHandleForCoupons>(Convert.ToString(responseDto.Result));
               coupons = handleForList.Result; 
            }

            return View(coupons);
        }

        [HttpGet]
        public IActionResult CreateCoupon()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoupon(CouponDto couponDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _couponService.AddCouponAsync(couponDto);

                if (response != null && response.IsSuccess)
                {
                    
                    TempData["Success"] = "Coupon added successfully.";                    
                    return RedirectToAction("Index");
                }
                else if (!response.IsSuccess)
                {

                    TempData["Error"] = response.Message;
                }
            }
            return View(couponDto);

        }

        [HttpGet]
        public async Task<IActionResult> UpdateCoupon(int couponId)
        {
            var response = await _couponService.GetCouponByIdAsync(couponId);
            CouponDto? couponDto;
            ResponseDto responseDto = new ResponseDto();
                        
            if (response != null && response.IsSuccess && response.Result != null) 
            {
                couponDto = new();
                //couponDto.

            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateCoupon(CouponDto couponDto)
        {
            if (ModelState.IsValid)
            {
                var response = await _couponService.UpdateCouponAsync(couponDto);

            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DeleteCoupon(int couponId)
        {
            var response =  await _couponService.DeleteCouponAsync(couponId);
            
            if(response != null && response.IsSuccess) 
            {
                TempData["Success"] = "Coupon deleted successfully";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Error"] = response?.Message;
                return RedirectToAction("Index");
            }

        }
    }
}

Mango.Web/Controllers/ProductController.cs
using Mango.Web.Models;
using Mango.Web.Service.IService;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
//using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Mango.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
		private readonly ICartService _cartService;

		public ProductController(IProductService productService, 
                                 ICartService cartService)
        {
            _productService = productService;
			_cartService = cartService;
		}

        [HttpGet]
        public async Task<IActionResult> Products()
        {
            var response = await _productService.GetProducts();
            List<ProductDto> products = new();
            if (response != null && response.IsSuccess)
            {
                var result = JsonConvert.DeserializeObject<DeserializeHandleForProducts>(Convert.ToString(response.Result));
                products = result.Result;
            }
            else if(response != null && !string.IsNullOrWhiteSpace(response.Message))
            {
                TempData["Error"] = "You are not authorized to view this page";
                return RedirectToAction("Index", "Home");
            }
            
            return View(products);
        }        

        [HttpGet]        
        public IActionResult CreateProduct()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ProductDetails(int productId)
        {
            var response = await _productService.GetProduct(productId);
            if(response != null && response.IsSuccess)
            {
                var deserialised = JsonConvert.DeserializeObject<DeserializeHandlerForProduct>(Convert.ToString(response.Result));
                return View(deserialised.Result);
            }
            else if(response != null && !string.IsNullOrWhiteSpace(response.Message))
            {
                TempData["Error"] = "You are not authorized to perform this operation";
                return RedirectToAction("Index", "Home");
            }
           
            var errors = ModelState.SelectMany(ms => ms.Value.Errors);

            if (errors.Any())
            {
                string commaseparatedError = string.Empty;

                foreach (var error in errors)
                {
                    commaseparatedError = string.Join(",", error.ErrorMessage);
                }

                ModelState.AddModelError("Errors", commaseparatedError);
            }

            return View(new ProductDetailsDto());
        }

        [HttpPost]
        public async Task<IActionResult> ProductDetails(ProductDetailsDto productDetailsDto)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    CartHeaderDto cartHeaderDto = new()
                    {
                        UserId = User.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Sub)?.Value,
                    };

                    ProductDto productDto = new()
                    {
                        CategoryName = productDetailsDto.CategoryName,
                        Count = productDetailsDto.Count,
                        Description = productDetailsDto.Description,
                        ImageUrl = productDetailsDto.ImageUrl,
                        Name = productDetailsDto.Name,
                        ProductId = productDetailsDto.ProductId,
                        ProductPrice =productDetailsDto.ProductPrice.Value,
                    };

                    CartDetailsDto cartDetailsDto = new()
                    {
                        //Count = productDto.Count.Value,
                        ProductDto = productDto,                        
                    };

                    CartDto cartDto = new()
                    {
                        CartHeaderDto = cartHeaderDto,
                        CartDetailsDto = new HashSet<CartDetailsDto> { cartDetailsDto }
                    };
                    
                    var responseDto = await _cartService.UpsertCart(cartDto);
                    
                    if(responseDto != null && responseDto.IsSuccess) 
                    {
                        TempData["Success"] = "Product successfully added to the cart";
                        return RedirectToAction("Index", "ShoppingCart");
                    }
                }
            }
            catch(Exception ex) 
            { 
                Console.WriteLine(ex.Message);
            }

            return View(productDetailsDto);
        }

        [HttpPost]
        public async Task<IActionResult> CreateProduct(ProductDto productDto)
        {
            try
            {                
                if (ModelState.IsValid)
                {
                    ResponseDto response = await _productService.CreateNewProduct(productDto);
                    if (response != null && response.IsSuccess)
                    {
                        return RedirectToAction("Products");
                    }
                    
                    if (response != null && !response.IsSuccess)
                    {
                        TempData["Error"] = response.Message;
                    }
                }                                                
            } 
            catch (Exception ex) 
            { 
                Console.WriteLine(ex.ToString());
            }

            return View(productDto);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateProduct(int productId)
        {
            var responseDto = await _productService.GetProduct(productId);
            
            ProductDto productDto = new();
            
            if (responseDto != null && responseDto.IsSuccess)
            {
                var result = JsonConvert.DeserializeObject<DeserializeHandlerForProduct>(Convert.ToString(responseDto.Result));
                
                var productDetailsDto = result.Result;

                productDto.ImageUrl = productDetailsDto.ImageUrl;
                productDto.ProductPrice = productDetailsDto.ProductPrice.Value;
                productDto.Description = productDetailsDto.Description;
                productDto.ProductId = productDetailsDto.ProductId;
                productDto.CategoryName = productDetailsDto.CategoryName;
                //productDto.Count = productDetailsDto.Count;

                return View(productDto);
            }
            else if (responseDto != null && !responseDto.IsSuccess)
            {
                TempData["Error"] = responseDto.Message;
            }
            
            return View(productDto);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateProduct(ProductDto productDto)
        {
            var response = await _productService.UpdateProduct(productDto);

            if(response != null && response.IsSuccess)
            {
                TempData["Success"] = "Product updated successfully";

                return RedirectToAction("Products");
            }
            else if (response != null && !response.IsSuccess)
            {
                TempData["Error"] = response.Message;
            }

            return View(productDto);   
        }

        [HttpGet]
        public async Task<IActionResult> DeleteProduct(int productId)
        {
            var response = await _productService.DeleteProduct(productId);
            if(response != null && response.IsSuccess)
            {
                TempData["Success"] = "Product deleted successfully";
                return RedirectToAction("Products");
            }
            else if (response != null && !response.IsSuccess)
            {
                TempData["Error"] = response.Message;
            }

            return RedirectToAction("Products");
        }

    }
}

Mango.Web/Views/Shared/_Layout.cshtml
@using System.IdentityModel.Tokens.Jwt
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mango.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Mango.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Coupon" asp-action="Index">Coupons</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item active me-5">
                            <a class="nav-link active" asp-action="Index" asp-controller="Home">
                                Home                            
                            </a>
                        </li>
                        <li class="nav-item pt-2 me-5"><a class="nav-link active" asp-controller="Coupon" asp-action="Index">Coupons</a></li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("SuperAdmin"))
                        {
                            <li class="nav-item pt-2 me-5"><a class="nav-link active" asp-controller="Coupon" asp-action="CreateCoupon">Add coupons</a></li>
                        }
                    </ul>  
                    <ul class ="navbar-nav me-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item"><a class="nav-link active" asp-action="Login" asp-controller="Auth">Login </a></li>
                            <li class="nav-item"><a class="nav-link active" asp-action="RegisterUser" asp-controller="Auth">Registration </a></li>
                        }
                        else
                        {
                            <li class="nav-link mt-2">@User.Identity.Name, 
                                                <p>@(User.Claims.FirstOrDefault(cl => cl.Type == JwtRegisteredClaimNames.Email).Value)</p></li>
                            <li class="nav-link"><a class="nav-link" asp-action="Signout" asp-controller="Auth">Signout</a></li>
                            <li class="nav-link"><a class="nav-link" asp-action="Products" asp-controller="Product">Products</a></li>
                            <li class="nav-item mt-2">
                                <a class="nav-link" asp-action="Index" asp-controller="ShoppingCart"><i class="bi bi-cart"></i></a>
                            </li>
                        }

                        
                    </ul>
                </div>
            </div>
        </nav>        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_Notifications" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Mango.Web - <a asp-area="" asp-controller="Coupon" asp-action="Index">Home</a>
            <span>Made with Love <i class="bi bi-heart-fill"></i> by Abhishek M Jadhav</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Mango.Web/Views/Shared/_Notifications.cshtml
@if (TempData["Error"] != null) 
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["Error"]')
    </script>
}    
@if(TempData["Success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["Success"]')
    </script>
}